// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9rEWaYc348Zt2ZXsb3WPOffQZrGk9bXg',
    appId: '1:492841988277:web:965e269654b4708157cefc',
    messagingSenderId: '492841988277',
    projectId: 'talentsik-90c50',
    authDomain: 'talentsik-90c50.firebaseapp.com',
    storageBucket: 'talentsik-90c50.firebasestorage.app',
    measurementId: 'G-S6E22HZDEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4EiqSe6GfDxVzMWrm2N2eM7DoKbV-Ec',
    appId: '1:492841988277:android:43f6eac5c2cd939c57cefc',
    messagingSenderId: '492841988277',
    projectId: 'talentsik-90c50',
    storageBucket: 'talentsik-90c50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHuACdkIkaBNOwFzs3xA3a_DCNaHs3R8',
    appId: '1:492841988277:ios:bcbb8beb476ffca857cefc',
    messagingSenderId: '492841988277',
    projectId: 'talentsik-90c50',
    storageBucket: 'talentsik-90c50.firebasestorage.app',
    iosBundleId: 'com.example.talentseek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHuACdkIkaBNOwFzs3xA3a_DCNaHs3R8',
    appId: '1:492841988277:ios:bcbb8beb476ffca857cefc',
    messagingSenderId: '492841988277',
    projectId: 'talentsik-90c50',
    storageBucket: 'talentsik-90c50.firebasestorage.app',
    iosBundleId: 'com.example.talentseek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9rEWaYc348Zt2ZXsb3WPOffQZrGk9bXg',
    appId: '1:492841988277:web:b5f6ff422ec770ca57cefc',
    messagingSenderId: '492841988277',
    projectId: 'talentsik-90c50',
    authDomain: 'talentsik-90c50.firebaseapp.com',
    storageBucket: 'talentsik-90c50.firebasestorage.app',
    measurementId: 'G-FZDWSHR58W',
  );
}
